/**
 * Created by wupeiying on 2015/12/30.
 */
define({
    MAP : {
        '101' : {typeTxt: '新增机构', icon: 'icon-plus'},
        '102' : {typeTxt: '新增商户', icon: 'icon-plus'},
        '103' : {typeTxt: '新增机构拓展员', icon: 'icon-plus'},
        '104' : {typeTxt: '新增直销拓展员', icon: 'icon-plus'},
        '106' : {typeTxt: '新增外卡商户', icon: 'icon-plus'},
        '107' : {typeTxt: '新增二维码商户/好哒商户', icon: 'icon-plus'},
        '108' : {typeTxt: '集团商户(总店)', icon: 'icon-plus'},
        '110' : {typeTxt: '集团商户(门店)', icon: 'icon-plus'},
        '201' : {typeTxt: '修改机构信息', icon: 'icon-plus'},
        '202' : {typeTxt: '修改商户信息', icon: 'icon-plus'},
        '203' : {typeTxt: '修改用户信息', icon: 'icon-plus'},
        '204' : {typeTxt: '修改终端信息', icon: 'icon-plus'},
        '205' : {typeTxt: '商户修改银行卡号', icon: 'icon-plus'},
        '206' : {typeTxt: '机构拓展员实名认证审核', icon: 'icon-plus'},
        '207' : {typeTxt: '商户补充资料审核', icon: 'icon-plus'},
        '208' : {typeTxt: '直销拓展员补充资料审核', icon: 'icon-plus'},
        '209' : {typeTxt: '开放注册用户补充资料审核', icon: 'icon-plus'},
        '301' : {typeTxt: '申请生产终端', icon: 'icon-plus'},
        '302' : {typeTxt: '申领终端', icon: 'icon-plus'},
        '303' : {typeTxt: '申购终端', icon: 'icon-plus'},
        '304' : {typeTxt: '申请提额', icon: 'icon-plus'},
        '305' : {typeTxt: '新增直销拓展员-新', icon: 'icon-plus'},
        '306' : {typeTxt: '盒伙人对私转对公', icon: 'icon-plus'}
    },
    SUBTYPE_MAP : {
        '101' : '新增机构',
        '102' : '新增商户',
        '103' : '新增机构拓展员',
        '104' : '新增直销拓展员',
        '106' : '新增外卡商户',
        '107' : '新增二维码商户/好哒商户',
        '108' : '集团商户(总店)',
        '110' : '集团商户(门店)',
        '201' : '修改机构信息',
        '202' : '修改商户信息',
        '203' : '修改用户信息',
        '204' : '修改终端信息',
        '205' : '商户修改银行卡号',
        '206' : '机构拓展员实名认证审核',
        '207' : '商户补充资料审核',
        '208' : '直销拓展员补充资料审核',
        '209' : '开放注册用户补充资料审核',
        '301' : '申请生产终端',
        '302' : '申领终端',
        '303' : '申购终端',
        '304' : '申请提额',
        '305' : '新增直销拓展员-新',
        '306' : '盒伙人对私转对公'
    }
});