define({
	root: {
		//@link(value="role")
		'role' : '角色',
		'role.code': '编号',
		'role.flag': '可见级别',
		'role.descr': '描述',
		'role.flag.all':'所有级别可见',
		'role.flag.level-one':'仅一级可见',
		'role.flag.level-zero':'仅0级可见',
		'role.operation':'操作按钮',

		//@link(value="rule")
		'rule.code': '编号',
		'rule.range.txt': '范围',
		'rule.branch.txt': '机构',
		'rule.descr': '描述',
		'rule.operation':'操作按钮',
		'rule.type.0': '自定义规则',
		'rule.type.1': '本机构全部',
		'rule.type.2': '下级全部机构',
		'rule.type.3': '本机构所有拓展员',
		'rule.type.4': '仅查看自己拓展的',
		'rule.branchsel.label': '选择机构',
		'rule.oprsel.label': '选择操作员',

		//@link(value="role-group")
		'role-group.txt' : '角色组',
		'role-group.name': '名称',
		'role-group.code': '编号',
		'role-group.branch.txt': '机构编号',
		'role-group.branchName.txt' : '机构名称',
		'role-group.descr': '描述',
		'role-group.operation':'操作按钮',

		'org.txt' : '机构',
		'rule.txt':'规则',
		'rule-point.txt':'规则元素',

		'operator.txt' : '操作员',
		'rule.type.curlevel': '当前级别',
		'rule.type.lower.all': '下级所有',
		'rule.type.lower.devleper': '下级拓展员',
		'rule.type.deprules': '依据所选规则',

		//@link(value="org")
		'org.name': '机构名称',
		'org.code': '机构编号',
		'org.address.txt':'地址',
		'org.tel.txt':'联系人固话',
		'org.discId.txt':'手续费模型ID',
		'org.cardType.txt':'证件类型',
		'org.cardType.idcard':'身份证',
		'org.cardNo.txt':'证件号码',
		'org.endDate.txt':'身份证有效期',
		'org.mobile.txt':'手机号码',
		'org.contact.txt':'联系人',
		'org.oneAgent.txt':'一级代理商',
		'org.up.txt':'上级机构',
		'org.belog-level.txt':'所属级别',
		'org.type.txt':'类别',
		'org.type.0':'其它',
		'org.type.1':'省代',
		'org.type.2':'市代',
		'org.status.txt':'状态',
		'org.status.normal':'正常',
		'org.status.submit.perform':'提交待审核',
		'org.status.stop':'停用',
		'org.status.cancel':'注销',
		'org.status.revise.edit':'拒绝待修改',
		'org.status.save':'机构新增保存',

		'org.isStlm.txt':'是否参与分润',
		'org.isStlm.0':'否',
		'org.isStlm.1':'是',
		'org.operation.txt':'操作按钮',
		'org.level.txt': '机构等级',

		//@link(value="log")
		'log.txt':'日志',
		'log.model':'操作业务模块',
		'log.resName':'操作资源名称',
		'log.type':'操作类型',
		'log.brhCode':'机构编号',
		'log.brhName':'机构名称',
		'log.status':'操作状态',
		'log.oprId':'操作员编号',
		'log.oprName':'操作员名称',
		'log.desc':'操作内容',
		'log.oprTime':'操作时间',
		'log.keyId':'关键信息ID',
		'log.keyName':'关键信息名称',
		'log.soureInfo':'原信息',
		'log.modifyInfo':'修改过的信息',

		//@link(value="user")
		'user.id':'操作员编号',
		'user.name': '真实姓名',
		'user.oneAgent': '一级代理商',
		'user.code': '编号',
		'user.brhCode': '机构编号',
		'user.brhLevel': '所属机构级别',
		'user.brhName': '所属机构',     //'机构名称',
		'user.login.name': '登录帐号',
		'user.role-group.name': '角色组名称',
		'user.role-group': '角色组',
		'user.rule.id':'规则编号',
		'user.rule.name': '管辖范围',
		'user.is.explorer.txt': '是否为拓展员',
		'user.oprInviteCode':'推荐码',
		'user.oprBeinvitedCode':'被推荐码',

		'user.cardNo.txt' : '身份证号码',
		'user.idCardFront.txt' : '身份证照片',
		'user.personWithIdCard.txt' : '手持身份证照片',
		'user.cardType.txt' : '证件类型',

		'user.gender': '性别',
		'user.status': '用户状态',
		'user.register.date': '录入时间',
		'user.tel': '固定电话',
		'user.mobile': '手机号码',
		'user.email': '邮箱',
		'user.not.explorer': '非拓展员',
		'user.is.explorer': '是拓展员',
		'user.gender.male':'男',
		'user.gender.female':'女',
		'user.status.normal':'正常',
		'user.status.submit.perform':'提交待审核',
		'user.status.revise.edit':'拒绝待修改',
		'user.status.save':'用户新增保存',
		'user.status.stop':'停用',
		'user.status.off':'注销',
		'user.operation':'操作按钮',

		//@link(value="auth")
		//
		'privilege.txt':'权限',
		'auth.txt':'权限',
		'auth.module': '模块',
		'auth.res.code': '资源编号',
		'auth.res.name': '资源名称',
		'auth.operation':'操作按钮'
	}

});