define({
    root: {
        'batMainCtlDetail.txt':'批处理主控任务流水表',
        'bat.main.ctl.detail.date.settlmt':'清算日期',
        'bat.main.ctl.detail.timeNode':'时间节点',
        'bat.main.ctl.detail.settle.num':'同周期清算次数',
        'bat.main.ctl.detail.bat.no':'批量编号',
        'bat.main.ctl.detail.proc.name':'批量程序名',
        'bat.main.ctl.detail.priority':'优先级',
        'bat.main.ctl.detail.state':'运行状态',
        'bat.main.ctl.detail.run.proc.quantity':'设置进程数',
        'bat.main.ctl.detail.commit.quantity':'单次提交记录数',
        'bat.main.ctl.detail.chd.count':'子进程数量',
        'bat.main.ctl.detail.task.assign.state':'任务分配状态',
        'bat.main.ctl.detail.task.start.flag':'是否指定主机',
        'bat.main.ctl.detail.descr':  '任务描述',    //'批量任务描述',
        'bat.main.ctl.detail.note':'运行描述',
        'bat.main.ctl.detail.rec.opr.id':'记录柜员号',
        'bat.main.ctl.detail.rec.upd.opr':'修改柜员号',
        'bat.main.ctl.detail.rec.crt.time':'记录创建时间',
        'bat.main.ctl.detail.rec.upd.time':'记录修改时间',


        'channelAccount.txt':'渠道财务信息表',
        'channel.account.stlm.date':'账务日期',
        'channel.account.id' : 'id',
        'channel.account.cups.no':'渠道编号',
        'channel.account.cups.name':'渠道名称',
        'channel.account.tx.amt':'对平交易金额',  // '交易金额'
        'channel.account.cup.fee': '对平手续费',  // '手续费',
        'channel.account.in.amt':'对平应收金额',  // '应收金额'
        'channel.account.resv.amt1':'渠道账单应收金额',
        'channel.account.real.amt':'实收金额',
        'channel.account.real.in.dif':'实收差异',
        'channel.account.recv.flag':'收款标示',
        'channel.account.oprMsg2':'处理描述',
        'channel.account.in.acct.id':'收款银行ID',
        'channel.account.bank.name':'收款银行名称',
        'channel.account.opr.name':'确认收银员',
        'channel.account.auth.opr':'确认收银员',
        'channel.account.auth.tme':'确认收款时间',


        'channel-txn.recvFlag.0':'已对账且对平',
        'channel-txn.recvFlag.1':'已对账但不平',
        'channel-txn.recvFlag.2':'第三方流水未对账',
        'channel-txn.recvFlag.3':'撤销或交易已撤销',
        'channelTxn.txt':'渠道流水信息表',
        'channel.txn.stlm.date':'清算日期',
        'channel.txn.tx.date':'交易日期',
        'channel.txn.tx.time':'交易时间',
        'channel.txn.trace.no':'平台流水',
        'channel.txn.cup.name':'渠道名称',
        'channel.txn.cup.key':'第三方手KEY',
        'channel.txn.result.flag':'结果标示',
        'channel.txn.cups.no':'交易渠道',//渠道编号
        'channel.txn.term.no':'第三方终端号',
        'channel.txn.ac.no':'交易卡号',
        'channel.txn.ac.bank.no':'发卡行编号',
        'channel.txn.bank.name':'发卡行',
        'channel.txn.tx.amt':'交易金额',
        'channel.txn.cup.fee':'第三方手续费',
        'channel.txn.tx.code':'交易类型',
        'channel.txn.sys.ref.no':'系统检索号',
        'channel.txn.brf':'摘要',
        'channel.txn.fill':'备注',
        'channel.txn.rec.crt.ts':'记录创建时间',
        'channel.txn.rec.upd.ts':'记录修改时间',



        'settleError.txt':'入账差错信息表',
        'settle.error.id': 'id',
        'settle.error.settle.date':'清算日期',
        'settle.error.in.date':'入账日期',
        'settle.error.batch.no':'批次号',
        'settle.error.trace.no':'流水号',

        //add extra message
        'settle.error.branch.name' : '机构名称',
        'settle.error.branch.user.name' : '管理员姓名',
        'settle.error.branch.phone' : '管理员手机',
        'settle.error.branch.mobile' : '管理员电话',
        'settle.error.mcht.name' : '商户名称',
        'settle.error.user.name' : '主用户姓名',
        'settle.error.user.phone' : '主用户手机',
        //add end

        'settle.error.trace.error.type' : '错误类型',
        'settle.error.do.flag':'处理标示',
        'settle.error.ret.no':'响应流水号',
        'settle.error.ret.code':'响应码',
        'settle.error.ret.msg':'响应信息',
        'settle.error.opr.date':'处理日期',
        'settle.error.opr.no':'处理人员',
        'settle.error.opr.name' : '处理人员',
        'settle.error.next.date':'处理后参加清算日期',
        'settle.error.next.do':'原因及处理描述',
        'settle.error.mcht.no':'商户编号',
        'settle.error.settle.brh.id':'清算机构号',
        'settle.error.settle.acct.type':'账户类型',
        'settle.error.settle.bank.no':'账户开户行号',
        'settle.error.settle.bank.name':'账户开户行名称',
        'settle.error.settle.bank.address':'账户开户行地址',
        'settle.error.settle.bank.code':'账户开户行地区编码',
        'settle.error.settle.acct.name':'账户名称',
        'settle.error.settle.acct':'账户账号',
        'settle.error.settle.amt':'清算金额',
        'settle.error.other.amt':'其它金额',
        'settle.error.remark':'备注',
        'settle.error.rec.create.time':'记录创建时间',
        'settle.error.rec.upd.time':'记录修改时间',
        'settle.error.discCycle' : '结算周期',


        'settleSum.txt':'清算汇总表',
        'settle.sum.id' : 'id',
        'settle.sum.settle.date':'清算日期',
        'settle.sum.timeNode'   :'时间节点',
        'settle.sum.settle.num':'同周期清算次数',
        'settle.sum.settle.desc':'清算描述',
        'settle.sum.do.flag':'操作标志',
        'settle.sum.total.num':'总笔数',
        'settle.sum.total.amt':'总金额',
        'settle.sum.succ.num':'成功笔数',
        'settle.sum.succ.amt':'成功金额',
        'settle.sum.fail.num':'失败笔数',
        'settle.sum.fail.amt':'失败金额',
        'settle.sum.unknow.num':'不确定笔数',
        'settle.sum.unknow.amt':'不确定金额',
        'settle.sum.done.num':'已完成批次数',
        'settle.sum.settle.mode':'入账方式',
        'settle.sum.same.bank.flag':'同行是否单独成一批次',
        'settle.sum.batch.num':'批次数量',
        'settle.sum.sort.level':'排序优先级',
        'settle.sum.opr.id':'操作员',
        'settle.sum.opr.name':'操作员名称',
        'settle.sum.opr.msg1':'操作员描述',
        'settle.sum.rec.create.time':'记录创建时间',
        'settle.sum.rec.opr.time':'操作时间',
        'settle.sum.rec.in.time':'入账时间',
        'settle.sum.inalienable': '划分批次',




        'settleTxn.txt':'清算流水表',
        'settle.txn.settle.date':'清算日期',
        'settle.txn.in.date':'入账日期',
        'settle.txn.id' : 'id',
        'settle.txn.batch.no':'批次号',
        'settle.txn.trace.no':'流水号',
        'settle.txn.result.flag':'结果标示',
        'settle.txn.ret.no':'响应流水号',
        'settle.txn.ret.code':'响应码',
        'settle.txn.ret.msg':'响应信息',
        'settle.txn.mcht.no':'商户编号',
        'settle.txn.settle.brh.id':'清算机构号',
        'settle.txn.settle.acct.type':'账户类型',
        'settle.txn.settle.bank.no':'账户开户行号',
        'settle.txn.settle.bank.nm':'开户行',
        'settle.txn.settle.bank.addr':'账户开户行地址',
        'settle.txn.settle.bank.code':'账户开户行地区编码',
        'settle.txn.settle.acct.nm':'账户名',
        'settle.txn.settle.acct':'卡号',
        'settle.txn.settle.amt':'清算金额',
        'settle.txn.other.amt':'其它金额',
        'settle.txn.remark':'备注',
        'settle.txn.rec.create.time':'记录创建时间',
        'settle.txn.rec.upd.time':'记录修改时间',
        'settle.sum.discCycle' : '结算周期',



        'stlmAccount.txt':'清算收付款账户信息表',
        'stlm.account.id' : 'id',
        'stlm.account.mode':'账户种类',
        'stlm.account.is.default':'是否默认账户',
        'stlm.account.type':'账户类型',
        'stlm.account.no':'账户账号',
        'stlm.account.cust.no':'客户号',
        'stlm.account.name':'账户名称',
        'stlm.account.status':'账户状态',
        'stlm.account.bank.no':'账户开户行号',
        'stlm.account.bank.name':'开户行',
        'stlm.account.zbank.no':'账户开户支行号',
        'stlm.account.zbank.nm':'账户开户支行名称',
        'stlm.account.zbank.addr':'账户开户支行地址',
        'stlm.account.zbank.code':'账户开户支行地区号',
        'stlm.account.net.no':'账户网银支付号',
        'stlm.account.union.no':'账户联行号',
        'stlm.account.balance':'账户余额',
        'stlm.account.last.operater.id':'最后更新操作员',
        'stlm.account.last.operater.name':'最后更新操作员',
        'stlm.account.last.update.time':'最后更新时间',



        'stlmError.txt':'差错交易信息表',
        'stlm.error.id' : 'id',
        'stlm.error.stlm.date'  : '对账日期',
        'stlm.error.tx.date'  : '交易日期',
        'stlm.error.tx.time'  : '交易时间',
        'stlm.error.trace.no'  : '平台流水',
        'stlm.error.result.flag'  : '处理结果',
        'stlm.error.opr.date'  : '处理日期',
        'stlm.error.opr.no'  : '处理人员',
        'stlm.error.next.date'  : '处理后参加清算日期',
        'stlm.error.next.do'  : '处理描述',   //'原因及处理描述',
        'stlm.error.err.type'  : '差错类型',
        'stlm.error.err.desc'  : '差错描述',
        'stlm.error.stlm.type'  : '对账不平类型',
        'stlm.error.ibox.no'  : '盒子编号',
        'stlm.error.order.no'  : '订单号',
        'stlm.error.cups.no'  : '交易渠道',
        'stlm.error.ac.no'  :  '交易卡号',            //'主账户',
        'stlm.error.ac.bank.no'  : '账户开户行',
        'stlm.error.ac.type.no' : '卡类型',
        'stlm.error.user.id'  : '用户编号',
        'stlm.error.userName' : '用户姓名',
        'stlm.error.phone' : '用户手机',
        'stlm.error.email' : '用户邮箱',
        'stlm.error.tx.amt'  : '交易金额',
        'stlm.error.fee.amt'  : '手续费',   //'手续费金额',
        'stlm.error.cup.fee'  : '第三方手续费',
        'stlm.error.tx.code'  : '交易代码',
        'stlm.error.tx.name'  : '交易名称',
        'stlm.error.tx.sub.code'  : '子交易码',
        'stlm.error.brno'  : '交易机构号',
        'stlm.error.longitude'  : '交易经度',
        'stlm.error.latitude'  : '交易纬度',
        'stlm.error.sys.ref.no'  : '检索参考号',
        'stlm.error.ibox41'  : '本地终端标识',
        'stlm.error.fd41'  : '受卡机终端标识',
        'stlm.error.ibox42'  : '商户号',
        'stlm.error.fd42'  : '受卡方标识码',
        'stlm.error.ibox43'  : '商户名称',
        'stlm.error.fd43'  : '受卡方名称地址',
        'stlm.error.rec.crt.time'  : '记录创建时间',
        'stlm.error.rec.upd.time'  : '记录修改时间',
        'stlm.error.opr.name' : '处理人员',
        'stlm.error.user.name' : '用户名',
        'stlm.error.discCycle' : '结算周期',



        'stlmRepair.txt':'账单调整表',
        'stlm.repair.id' : 'id',
        'stlm.repair.repair.date' : '调账日期',
        'stlm.repair.result.flag' : '结果标示',

        //add extra message
        'stlm.repair.branch.name' : '机构名称',
        'stlm.repair.branch.user.name' : '管理员姓名',
        'stlm.repair.branch.phone' : '管理员手机',
        'stlm.repair.branch.mobile' : '管理员电话',
        'stlm.repair.mcht.name' : '商户名称',
        'stlm.repair.user.name' : '主用户姓名',
        'stlm.repair.user.phone' : '主用户手机',
        //add end

        'stlm.repair.repair.no' : '调账人员',
        'stlm.repair.repair.name' : '调账人员',
        'stlm.repair.opr.date' : '处理日期',
        'stlm.repair.opr.no' : '处理人员',
        'stlm.repair.opr.name' : '处理人员',
        'stlm.repair.next.date' : '处理后参加清算日期',
        'stlm.repair.next.do' : '处理描述',
        'stlm.repair.repair.flag' : '调账标示',
        'stlm.repair.repair.type' : '调账类型',
        'stlm.repair.repair.desc' : '调账描述',
        'stlm.repair.repair.amt' : '调账金额',
        'stlm.repair.now.amt' : '已调金额',
        'stlm.repair.ibox42' : '机构/商户编号',
        'stlm.repair.rec.create.time' : '记录创建时间',
        'stlm.repair.rec.upd.time' : '记录修改时间',


        'totalAccount.txt':'总账信息表',
        'total.account.id' : 'id',
        'total.account.stlm.date' : '账务日期',
        'total.account.up.balance' : '期初余额',
        'total.account.now.balance' : '期末余额',
        'total.account.cup.in.amt' : '渠道收款金额',
        'total.account.mcht.amt' : '商户清算金额',
        'total.account.brh.fee' : '机构支付金额',
        'total.account.draw.amt' : '公司提现金额',
        'total.account.other.in.amt' : '其它收款金额',
        'total.account.other.out.amt' : '其它付款金额',
        'total.account.other.unknow.amt' : '付款未确定金额',



        'totalAccountDetail.txt':'总账手动维护明细表',
        'total.account.detail.id': 'id',
        'total.account.detail.stlm.date' : '账务日期',
        'total.account.detail.stlm.type' : '操作类型',  //'账务维护类型',
        'total.account.detail.stat' : '审核结果',  //'状态',
        'total.account.detail.out.acct.no' : '付款账户',
        'total.account.detail.in.acct.no' : '收款账户',
        'total.account.detail.opr.name' : '提交人', //'操作员名称',
        'total.account.detail.opr.name2' : '审核人',   //'复审员名称',
        'total.account.detail.out.acct.id' : '付款账户',
        'total.account.detail.in.acct.id' : '收款账户',
        'total.account.detail.realetive.account' : '相关账户',
        'total.account.detail.tx.amt' : '交易金额',
        'total.account.detail.opr.id' : '提交人',  //'操作员',
        'total.account.detail.opr.id2' : '审核人',   //'复审员',
        'total.account.detail.opr.msg' : '操作描述',
        'total.account.detail.opr.msg2' : '审核描述',   //'复审描述',
        'total.account.detail.rec.opr.time' : '操作时间',
        'total.account.detail.rec.opr.time2' : '复审时间',


        'settleControl.txt' : '清算控制表',
        'settle.control.settle.date' : '清算日期',
        'settle.control.timeNode'  : '时间节点',
        'settle.control.settle.num' : '清算次数',
        'settle.control.in.date' : '入账日期',
        'settle.control.batch.no' : '批次号',
        'settle.control.ctl.flag' : '清算标志',
        'settle.control.pay.bank' : '中转银行',
        'settle.control.acct.no' : '付款账号',
        'settle.control.acct.un' : '付款行联行号',
        'settle.control.acct.name' : '付款账号名称',
        'settle.control.settle.mode' : '入账方式',
        'settle.control.host.name' : '银企直联前置机IP',
        'settle.control.host.port' : '银企直联前置机端口号',
        'settle.control.total.num' : '总笔数',
        'settle.control.total.amt' : '总金额',
        'settle.control.succ.num' : '成功笔数',
        'settle.control.succ.amt' : '成功金额',
        'settle.control.fail.num' : '失败笔数',
        'settle.control.fail.amt' : '失败金额',
        'settle.control.unknow.num' : '未确认笔数',
        'settle.control.unknow.amt' : '未确认金额',
        'settle.control.opr.id1' : '初审员',
        'settle.control.opr.id2' : '复审员',
        'settle.control.opr.msg1' : '操作描述',
        'settle.control.opr.msg2' : '复审描述',
        'settle.control.in.msg' : '操作描述',
        'settle.control.rec.create.time' : '记录创建时间',
        'settle.control.rec.opr.time1' : '操作时间',
        'settle.control.rec.opr.time2' : '复审时间',
        'settle.control.rec.in.time' : '入账时间',

        'settle.control.bank.name' : '账户开户行',
        'settle.control.bank.no'   : '账户开户行号',
        'settle.control.cust.no'   : '付款客户号',
        'settle.control.opr.name1' : '操作员',
        'settle.control.opr.name2' : '复审员名称' ,
        'settle.control.remark': '批次描述',



        "bat-main-ctl-detail.state.0"  :  "未运行",
        "bat-main-ctl-detail.state.1"  :  "正在运行",
        "bat-main-ctl-detail.state.2"  :  "运行成功",
        "bat-main-ctl-detail.state.3"  :  "运行失败",
        "bat-main-ctl-detail.teskAssignState.0"  :  "未分配",
        "bat-main-ctl-detail.teskAssignState.1"  :  "分配中",
        "bat-main-ctl-detail.teskAssignState.2"  :  "已分配",
        "bat-main-ctl-detail.taskStartFlag.0"  :  "不支持",
        "bat-main-ctl-detail.taskStartFlag.1"  :  "支持",
        "bat-main-ctl-detail.recOprId.0"  :  "未启",
        "bat-main-ctl-detail.recOprId.1"  :  "机构报备清分清算全部",
        "bat-main-ctl-detail.recOprId.2"  :  "商户清分清算全部",
        "bat-main-ctl-detail.recOprId.3"   :  "节假日只做加载流水",


        "channel-account.recvFlag.0" : "初始化未核实",
        "channel-account.recvFlag.1" : "收到与应收相符款项",
        "channel-account.recvFlag.2" : "收到款项但与应收不一致",




        "settle-control.ctlFlag.0" : "批次确认完成",
        "settle-control.ctlFlag.1" : "批次对帐完成",
        "settle-control.ctlFlag.2" : "批次对帐中",
        "settle-control.ctlFlag.3" : "批次入账完成",
        "settle-control.ctlFlag.4" : "批次入账处理失败",
        "settle-control.ctlFlag.5" : "批次入账处理中",
        "settle-control.ctlFlag.6" : "选择付款通道及入账方式",
        "settle-control.ctlFlag.7" : "领取任务",
        "settle-control.ctlFlag.8" : "划分批次中", //由“待处理”改为“划分批次中”
        "settle-control.ctlFlag.9" : "初始化状态",
        "settle-control.settleMode.0" : "直接联机清算",
        "settle-control.settleMode.1" : "文件方式其它系统代理清算",



        "settle-error.doFlag.0" : "参入清算后并已清算",
        "settle-error.doFlag.1" : "处理后参入下一批清算",
        "settle-error.doFlag.2" : "处理后手工清算",
        "settle-error.doFlag.4" : "待自动清算",
        "settle-error.doFlag.5" : "自动清算中",
        "settle-error.doFlag.6" : "自动清算成功",
        "settle-error.doFlag.9" : "未处理",
        "settle-error.settleAcctType.0" : "对公",
        "settle-error.settleAcctType.1" : "对私",
        "settle-error.errType.1" : '入账失败',
        "settle-error.errType.2" : '入账未确认',

        "settle-sum.doFlag.0" : "入账完成",
        "settle-sum.doFlag.1" : "入账进行中",
        "settle-sum.doFlag.2" : "已拆分好批次",
        "settle-sum.doFlag.3" : "拆分批次前",
        "settle-sum.doFlag.9" : "初始化状态",
        "settle-sum.settleMode.0" : "直接联机清算",
        "settle-sum.settleMode.1" : "全部采用文件方式其它系统代理清算",
        "settle-sum.settleMode.2" : "混合清算",
        "settle-sum.sortLevel.0" : "按账户",
        "settle-sum.sortLevel.1" : "按金额",
        "settle-sum.samebankflag.0": "否",
        "settle-sum.samebankflag.1": "是",


        "settle-txn.resultFlag.0" : "入账成功",
        "settle-txn.resultFlag.1" : "入账失败",
        "settle-txn.resultFlag.2" : "超时",
        "settle-txn.resultFlag.3" : "入账受理成功",
        "settle-txn.resultFlag.4" : "提交请求",
        "settle-txn.resultFlag.5" : "已拆分批次",
        "settle-txn.resultFlag.6" : "初始化信息",
        "settle-txn.settleAcctType.0" : "对公",
        "settle-txn.settleAcctType.1" : "对私",

        "stlm-account.mode.0" : "仅为收款账户",
        "stlm-account.mode.1" : "仅为付款账户",
        "stlm-account.mode.2" : "即为收款又为付款",
        "stlm-account.isDefault.0" : "否",
        "stlm-account.isDefault.1" : "默认账户",
        "stlm-account.type.0" : "对公",
        "stlm-account.type.1" : "对私",
        "stlm-account.status.0" : "正常",
        "stlm-account.status.1" : "异常",


        "stlm-error.resultFlag.0" : "参入清算后并已清分",
        "stlm-error.resultFlag.1" : "处理后参加清算",
        "stlm-error.resultFlag.2" : "手工处理退货",
        "stlm-error.resultFlag.3" : "手工处理请款",
        "stlm-error.resultFlag.4" : "手工处理挂账",
        "stlm-error.resultFlag.5" : "手动退货",
        "stlm-error.resultFlag.6" : "补帐处理",
        "stlm-error.resultFlag.9" : "未处理",
        "stlm-error.errType.1" : "对账不平",
        "stlm-error.errType.2" : "风控拦截延迟清算",
        "stlm-error.errType.3" : "手工延迟清算",
        "stlm-error.errType.4" : "商户不正常延迟清算",
        "stlm-error.stlmType.0" : "对账平，处理异常",
        "stlm-error.stlmType.1" : "本地有，渠道没有",
        "stlm-error.stlmType.2" : "本地无，渠道有",
        "stlm-error.stlmType.3" : "本地与渠道金额不一致",
        "stlm-error.stlmType.4" : "本地与渠道账号不一致",
        //"stlm-error.acType.0" : "仅为收款账户",
        //"stlm-error.acType.1" : "仅为付款账户",
        //"stlm-error.acType.2" : "即为收款又为付款",

        //清算批次锁表
        'settle.lock.txt'          : '清算批次锁',
        'settle.lock.id'           : 'id',
        'settle.lock.control.id' : '关联清算控制表编号',
        'settle.lock.opr.lock.id' : '领取人编号',
        'settle.lock.opr.lock.name' : '领取人姓名',
        'settle.lock.opr.unlock.id' : '解锁人编号',
        'settle.lock.opr.unlock.name' : '解锁人姓名',
        'settle.lock.lock.flag' : '锁状态',
        'settle.lock.ip' : '绑定IP',
        'settle.lock.mac' : '网卡',
        'settle.lock.lock.time' : '领用时间',
        'settle.lock.unlock.time' : '解绑时间',
        'settle.lock.res' : '预留',

        'settle.lock.get.lock' : '已被领取加锁',
        'settle.lock.off.lock' : '已被解锁',

        "stlm-repair.resultFlag.0" : "参入清算后已纳入清算",
        "stlm-repair.resultFlag.1" : "处理后参加清算",
        "stlm-repair.resultFlag.2" : "处理后挂账",
        "stlm-repair.resultFlag.3" : "处理后用于退货",
        "stlm-repair.resultFlag.7" : "调账完毕",
        "stlm-repair.resultFlag.8" : "调账中",
        "stlm-repair.resultFlag.9" : "未处理",
        "stlm-repair.repairFlag.1" : "商户调账",
        "stlm-repair.repairFlag.2" : "机构调账",
        "stlm-repair.repairType.1" : "按金额调账",
        "stlm-repair.repairType.2" : "结算全部",



        "total-account-detail.stlmType.0" : "提现",
        "total-account-detail.stlmType.1" : "转账转出",
        "total-account-detail.stlmType.2" : "转账转入",


        'BranchSettleDetails.txt' :  '机构清算明细表',
        'branch.settle.details.settle.date' :  '清算日期',
        'branch.settle.details.in.date' :  '入账日期',
        'branch.settle.details.tx.date' :  '交易月份',
        'branch.settle.details.batch.no' :  '批次号',
        'branch.settle.details.trace.all' :  '总流水',
        'branch.settle.details.trace.no' :  '流水号',
        'branch.settle.details.result.flag' :  '结果标示',
        'branch.settle.details.result.desc' :  '清算处理描述',
        'branch.settle.details.tx.num' :  '交易总笔数',
        'branch.settle.details.tx.amt' :  '交易总金额',
        'branch.settle.details.fee.amt' :  '手续费金额',
        'branch.settle.details.base.amt' : '基准手续费',
        'branch.settle.details.cups.fee' :  '第三方手续费',
        'branch.settle.details.in.fee' :  '手续费净额',
        'branch.settle.details.other.fee' :  '其它费用',
        'branch.settle.details.rate' :  '手续费净额扣率',
        'branch.settle.details.repair.amt' :  '调账金额',
        'branch.settle.details.unrepair.amt' :  '调账后清算金额',
        'branch.settle.details.uperr.amt' :  '上周期入账失败金额',
        'branch.settle.details.do.flag' :  '借贷标示',
        'branch.settle.details.settle.amt' :  '分润金额',
        'branch.settle.details.settle.brh.id' :  '清算机构号',
        'branch.settle.details.settle.brh.name' : '清算机构名称',
        'branch.settle.details.rec.create.time' :  '记录创建时间',
        'branch.settle.details.rec.upd.time' :  '记录修改时间',


        'branch.settle.details.result.flag.0' : '入账成功',
        'branch.settle.details.result.flag.1' : '入账失败',
        'branch.settle.details.result.flag.2' : '已汇总未付款',
        'branch.settle.details.result.flag.3' : '直接插入入账错误表进行手工清算',
        'branch.settle.details.result.flag.8' : '已人工选择可付款',
        'branch.settle.details.result.flag.9' : '初始化待选择',


        'MchtSettleDetail.txt'   : '商户清算明细',
        'mcht.settle.detail.id'  : 'id',
        'mcht.settle.detail.settle.date'  :  '清算日期',
        'mcht.settle.detail.timeNode'     :  '时间节点',
        'mcht.settle.detail.settleNum'    :  '清算次数',
        'mcht.settle.detail.in.date'  :  '入账日期',
        'mcht.settle.detail.tx.date'  :  '交易日期',
        'mcht.settle.detail.batch.no'  :  '批次号',
        'mcht.settle.detail.trace.no'  :  '流水号',
        'mcht.settle.detail.result.flag'  :  '结果标示',

        // 还需要商户名称，商户编号，扩展员，签约机构号。签约机构名
        'mcht.settle.detail.mcht.name'  :  '商户名称',
        'mcht.settle.detail.mcht.no'  :  '商户编号',
        'mcht.settle.detail.expand.name'  :  '拓展员',
        'mcht.settle.detail.branch.no'  :  '签约机构号',
        'mcht.settle.detail.branch.name'  :  '签约机构名',

        'mcht.settle.detail.tx.num'  :  '交易笔数',
        'mcht.settle.detail.tx.amt'  :  '本金',
        'mcht.settle.detail.settle.amt'  :  '清算金额',
        'mcht.settle.detail.fee.amt'  :  '手续费金额',
        'mcht.settle.detail.free.amt'  :  '优惠金额',
        'mcht.settle.detail.other.fee'  :  '其他费用',
        'mcht.settle.detail.repair.fee'  :  '调帐金额',
        'mcht.settle.detail.unrepair.fee'  :  '调账后清算金额',
        'mcht.settle.detail.uperr.amt'  :  '上周期入账失败金额',
        'mcht.settle.detail.result.desc'  :  '清算处理描述',
        'mcht.settle.detail.credit.num'  :  '贷记卡交易笔数',
        'mcht.settle.detail.credit.amt'  :  '贷记卡交易金额',
        'mcht.settle.detail.credit.percent'  :  '贷记卡交易占比',
        'mcht.settle.detail.rec.crt.ts'  :  '记录创建时间',
        'mcht.settle.detail.rec.upd.ts'  :  '记录修改时间',
        'mcht.settle.detail.flag'  :  '大额拆分状态',
        'mcht.settle.detail.pay.cups.no'  :  '出款通道编码',


        'mcht.settle.detail.result.flag0' : '入账成功',
        'mcht.settle.detail.result.flag1' : '入账失败',
        'mcht.settle.detail.result.flag2' : '未处理',
        'mcht.settle.detail.result.flag3' : '直接手工清算',


        'algo.detail.algoDate' :  '清分日期',
        'algoDetail.txt'      : '清分明细信息',
        'algo.detail.txTime'  : '交易时间',
        'algo.detail.txDate' :  '交易日期',
        'algo.detail.traceNo' :  '平台流水',
        'algo.detail.orderNo' :  '订单号',
        'algo.detail.settleMchtNO' :  '清算商户号',
        'algo.detail.settleMchtName' :  '清算商户名称',
        'algo.detail.tradeMchtNo' :  '交易商户编号',
        'algo.detail.tradeMchtName' :  '交易商户名称',
        'algo.detail.paymentMethod' :  '支付方式',
        'algo.detail.mchtBatchNo' :  '商户清算批次号',
        'algo.detail.mchtTraceNo' :  '商户清算流水号',
        'algo.detail.mchtFlag' :  '商户清算标示',
        'algo.detail.brhBatchNo' :  '机构清算批次号',
        'algo.detail.brhTraceNo' :  '机构清算流水号',
        'algo.detail.brhFlag' :  '机构清算标示',
        'algo.detail.settleBrhCode' :  '清算机构号',
        'algo.detail.settleBrhName' :  '清算机构名称',
        'algo.detail.txName' :  '交易名称',
        'algo.detail.ibox41' :  '终端编号',
        'algo.detail.acNo' :  '消费卡号',
        'algo.detail.acType' :  '账户类型',
        'algo.detail.acBankNo' :  '账户开户行',
        'algo.detail.txAmt' :  '交易金额',
        'algo.detail.feeAmt' :  '手续费金额',
        'algo.detail.cupFee' :  '第三方手续费',
        'algo.detail.servFee' :  '服务费分润',
        'algo.detail.brhFee' :  '机构服务费',
        'algo.detail.txCode' :  '其它费用',
        'algo.detail.iboxNo' :  '盒子编号',
        'algo.detail.discCycle' :  '结算周期',
        'algo.detail.recCreateTime' :  '记录创建时间',
        'algo.detail.recUpdTime' :  '记录修改时间',
        'algo.detail.baseAmt'  :  '基准手续费',
        'algo.detail.brno': '签约机构号',
        'algo.detail.brName': '签约机构名',
        'algo.detail.expandName': '拓展员',


        'algo.detail.mchtFlag0'  :  '已结算',
        'algo.detail.mchtFlag1'  :  '未结算',
        'algo.detail.brhFlag0'   :  '已结算',
        'algo.detail.brhFlag1'   :  '未结算',

        'algo.detail.acType.0'   :  '对公',
        'algo.detail.acType.1'   :  '对私',

        'tradeTxn.txt'  : '交易流水信息表',
        'trade.txn.id'  :  'id',
        'trade.txn.orderNo'  :  '订单号',
        'trade.txn.date'  :  '交易日期',
        'trade.txn.time'  :  '交易时间',
        'trade.txn.traceNo'  :  '交易流水号',
        'trade.txn.amt'  :  '交易金额',
        'trade.txn.acNo'  :  '消费卡号',
        'trade.txn.iboxNo'  :  '终端编号',
        'trade.txn.branchName'  :  '机构名称',
        'trade.txn.brNo'  :  '机构号',
        'trade.txn.ibox43'  :  '商户名称',
        'trade.txn.ibox42'  :  '商户号',
        'trade.txn.userId'  :  '收银员编号',
        'trade.txn.userName'  :  '收银员',
        'trade.txn.userAccNo'  :  '商户结算账户',
        'trade.txn.expandName'  :  '拓展员',
        'trade.txn.cupsNo'  :  '交易渠道',
        'trade.txn.cupsName'  :  '交易渠道',
        'trade.txn.cupsMchtNo': '渠道商户号',
        'trade.txn.cupsMchtName': '渠道商户名',
        'trade.txn.name'  :  '交易类型',
        'trade.txn.stat'  :  '交易状态',
        'trade.txn.couponId'  :  '优惠卷号',
        'trade.txn.fdxxx'  :  '交易描叙',
        'trade.txn.fd37'  :  '检索参考号',
        'trade.txn.fd12'  :  '受卡方所在地时间',
        'trade.txn.fd13'  :  '受卡方所在地日期',
        'trade.txn.fd39'  :  '错误码',  //'第三方响应码', bug #3665
        'trade.txn.discCycle': '结算周期',
        'trade.txn.errStr': '失败原因',

        'trade.txn.stat.0'  :  '交易成功',  //'成功应答',
        'trade.txn.stat.1'  :  '交易请求中',    //'请求',
        'trade.txn.stat.2'  :  '已冲正',
        'trade.txn.stat.3'  :  '已撤销',
        'trade.txn.stat.4'  :  '交易失败', //'已确认',
        'trade.txn.stat.5'  :  '部分退货',
        'trade.txn.stat.6'  :  '全额退货',
        'trade.txn.stat.7'  :  '交易异常(收到冲正交易)',


        'trade.txn.sub.code.30' : '余额查询',
        'trade.txn.sub.code.31' : '消费',
        'trade.txn.sub.code.32' : '消费冲正',
        'trade.txn.sub.code.33' : '消费撤销',
        'trade.txn.sub.code.34' : '消费撤销冲正',
        'trade.txn.sub.code.35' : '退货',
        'trade.txn.sub.code.50' : 'POS余额查询',
        'trade.txn.sub.code.51' : 'POS消费',
        'trade.txn.sub.code.52' : 'POS消费冲正',
        'trade.txn.sub.code.53' : 'POS消费撤销',
        'trade.txn.sub.code.54' : 'POS消费撤销冲正',
        'trade.txn.sub.code.55' : 'POS退货',

        'ukConfig.txt'   :  '清算账户UK配置表',

        'uk.config.id'  :  'id',
        'uk.config.oprId'  :  '操作员',
        'uk.config.oprName'  :  '操作员姓名',
        'uk.config.acctId'  :  '收付款账户',
        'uk.config.acctName'  :  '清算收付款账户',
        'uk.config.ukUser'  :  'uk用户',


        'brh.fee.txt': '代理商结算分润报表',

        'brh.fee.settle.brh.code':'代理商ID',
        'brh.fee.brh.name':'代理商名称',
        'brh.fee.settle.date':'清算日期',
        'brh.fee.tx.date':'账期',
        'brh.fee.result.flag':'状态',
        'brh.fee.tx.amt':'交易累计金额',
        'brh.fee.in.date':'入账日期',
        'brh.fee.tx.num':'交易笔数',
        'brh.fee.fee.amt':'商户签约手续费',
        'brh.fee.base.amt':'对外结算手续费',
        'brh.fee.settlefee':'代理服务费',
        'brh.fee.rate':'分润比率',
        'brh.fee.settle.amt':'清算金额',
        'brh.fee.repair.amt':'调账金额',
        'brh.fee.uprepair.amt':'调账后清算金额',
        'brh.fee.uperr.amt':'上周期入账失败金额',
        'brh.fee.pk':'pk',

        'mcht.detail.txt':'商户交易明细报表',

        'mcht.detail.mch.no':'商户编号',
        'mcht.detail.mcht.name':'商户名称',
        'mcht.detail.tx.name':'交易名称',
        'mcht.detail.tx.amt':'交易金额',
        'mcht.detail.fee.type':'费率模型类型',
        'mcht.detail.fee.value':'费率',
        'mcht.detail.fee.amt':'商户签约手续费',
        'mcht.detail.fee.settle':'对外结算手续费',
        'mcht.detail.cup.fee':'第三方手续费',
        'mcht.detail.out.amt':'应付金额',
        'mcht.detail.in.amt':'实收金额',
        'mcht.detail.trace.no':'平台流水',
        'mcht.detail.ac.no':'主账户',
        'mcht.detail.tx.date.time':'交易时间',
        'mcht.detail.settle.date':'清算日期',
        'mcht.detail.stat':'商户清算标示',
        'mcht.detail.ibox.no':'盒子编号',
        'mcht.detail.order.no':'订单号',
        'mcht.detail.sys.ref.num':'检索参考号',
        'mcht.detail.term.no':'本地终端标识',
        'mcht.detail.txn.mcht.no':'本地交易商户号',
        'mcht.detail.brh.code':'清算机构号',
        'mcht.detail.brh.name':'清算机构名称',
        'mcht.detail.disc.cycle':'商户结算周期',
        'mcht.detail.cups.no':'银联或银行编号',

        'batch.payment.txt':'批量支付报表',
        'batch.payment.seq':'序号',
        'batch.payment.ibox42':'商户号',
        'batch.payment.mcht.name':'商户名称',
        'batch.payment.tx.amt':'交易金额',
        'batch.payment.tx.num':'交易笔数',
        'batch.payment.fee.amt':'手续费金额',
        'batch.payment.repair.amt':'调账金额',
        'batch.payment.unrepair.amt':'调账后清算金额',
        'batch.payment.uperr.amt':'上周期入账失败金额',
        'batch.payment.credit.num':'贷记卡交易笔数',
        'batch.payment.credit.amt':'货记卡交易金额',
        'batch.payment.credit.percent':'货记卡交易占比',
        'batch.payment.settle.amt':'清算金额',
        'batch.payment.settle.acct.amt':'账户名称',
        'batch.payment.settle.acct':'账户账号',
        'batch.payment.zbank.name':'账户开户支行名称',
        'batch.payment.in.date':'入账日期',
        'batch.payment.settle.date':'清算日期',
        'batch.payment.result.status':'清算结果'

    }
});